{% set name = "update_checker" %}
{% set version = "0.15" %}
{% set sha256 = "dd39a9091d7f890bce3e193ec3d7052fe2c3b68b59ac61edd0627ebb3a0493ad" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - requests >=1.0.2

test:
  imports:
    - update_checker

about:
  home: https://github.com/bboe/update_checker
  license: BSD 2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  dev_url: https://github.com/bboe/update_checker
  summary: 'A python module that will check for package updates.'

extra:
  recipe-maintainers:
    - proinsias
