{% set version = "0.18.0" %}

package:
  name: update_checker
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/u/update_checker/update_checker-{{ version }}.tar.gz
  sha256: 6a2d45bb4ac585884a6b03f9eade9161cedd9e8111545141e9aa9058932acb13

build:
  number: 1
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - requests >=2.3.0

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - update_checker
  commands:
    - pip check

about:
  home: https://github.com/bboe/update_checker
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  dev_url: https://github.com/bboe/update_checker
  summary: A python module that will check for package updates.

extra:
  recipe-maintainers:
    - proinsias
    - bollwyvl
